config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @item = Item.last
    end

    def new
        @item = Item.new
    end

    def create
        Item.create(item_params)
        redirect_to root_path
    end

    private

    def item_params
        params.require(:item).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1 style="color: red"> Quizes 1 and 2 </h1>
<br/>
<%= link_to 'add item', new_item_path %>

<h2><%= @item.text %></h2>

app/views/items/new.html.erb
<h1>Add new Item</h1>
<%= simple_form_for @item do |f| %>
    <%= f.input :text %>
    <br/>
    <%= f.submit 'create'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>